### ISSUE TITLE
Möglichkeit mehrere Meter ohne Calc Plugin zu verwenden

### ISSUE THREAD

**Issue by DerAndereAndi** [evcc-io/config#70]
Es wäre hilfreich wenn mehrere PV- und oder Battery-Meter später bei der Site-Zuordnung automatisch addiert würden ohne vorher auf ein dediziertes calc-add-custom-Plugin-Konstrukt angewiesen zu sein.
Ich wüsste nämlich auch sonst nicht wie man das sonst einigermaßen einfach, verständlich und übersichtlich erzeugen könnte.

Also etwa so:
```yaml
site:
  title: Solarstromtankstelle
  meters:
    grid: shm
    pv: pv-dach, pv-garage
    battery: speicher-gross, speicher-klein
```
Und ja von mir aus auch natürlich gerne als List etc.

Oder die `usage` gleich in die Konfig mit reinziehen und die Zuordnung und Addition zur Site ganz automatisch machen ohne dass man das dort extra nochmal definieren muss.

Also z. B. dann am Ende so:
```yaml
meters:
- name: shm
  type: sma
  usage: grid
  uri: 192.168.178.90
- name: pv-dach
  type: sma
  usage: pv
  uri: 192.168.178.91
- name: pv-garage
  type: sma
  usage: pv
  uri: 192.168.178.92
- name: speicher
  type: sma
  usage: battery
  uri: 192.168.178.93

site:
  title: Solarstromtankstelle
```

__Originally posted by @premultiply in https://github.com/evcc-io/config/pull/69#issuecomment-920821152__
